/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppInfoRouteImport } from './routes/app-info'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as IdeRouteImport } from './routes/ide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PcbDesignerRouteImport } from './routes/pcb-designer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInfoRoute = AppInfoRouteImport.update({
  id: '/app-info',
  path: '/app-info',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeRoute = IdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PcbDesignerRoute = PcbDesignerRouteImport.update({
  id: '/pcb-designer',
  path: '/pcb-designer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app-info': typeof AppInfoRoute
  '/how-to-use': typeof HowToUseRoute
  '/ide': typeof IdeRoute
  '/login': typeof LoginRoute
  '/pcb-designer': typeof PcbDesignerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app-info': typeof AppInfoRoute
  '/how-to-use': typeof HowToUseRoute
  '/ide': typeof IdeRoute
  '/login': typeof LoginRoute
  '/pcb-designer': typeof PcbDesignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app-info': typeof AppInfoRoute
  '/how-to-use': typeof HowToUseRoute
  '/ide': typeof IdeRoute
  '/login': typeof LoginRoute
  '/pcb-designer': typeof PcbDesignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app-info'
    | '/how-to-use'
    | '/ide'
    | '/login'
    | '/pcb-designer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app-info'
    | '/how-to-use'
    | '/ide'
    | '/login'
    | '/pcb-designer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app-info'
    | '/how-to-use'
    | '/ide'
    | '/login'
    | '/pcb-designer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppInfoRoute: typeof AppInfoRoute
  HowToUseRoute: typeof HowToUseRoute
  IdeRoute: typeof IdeRoute
  LoginRoute: typeof LoginRoute
  PcbDesignerRoute: typeof PcbDesignerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-info': {
      id: '/app-info'
      path: '/app-info'
      fullPath: '/app-info'
      preLoaderRoute: typeof AppInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ide': {
      id: '/ide'
      path: '/ide'
      fullPath: '/ide'
      preLoaderRoute: typeof IdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcb-designer': {
      id: '/pcb-designer'
      path: '/pcb-designer'
      fullPath: '/pcb-designer'
      preLoaderRoute: typeof PcbDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppInfoRoute: AppInfoRoute,
  HowToUseRoute: HowToUseRoute,
  IdeRoute: IdeRoute,
  LoginRoute: LoginRoute,
  PcbDesignerRoute: PcbDesignerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
